"""Core data models for the crypto trading bot."""

from enum import Enum
from typing import Optional, Dict, Any
from pydantic import BaseModel, Field
from uuid import uuid4


class Regime(str, Enum):
    """Market regime classification."""
    TRENDING = "trending"
    RANGING = "ranging"
    HIGH_VOL = "high_vol"
    LOW_VOL = "low_vol"
    UNCERTAIN = "uncertain"


class RegimeSignal(BaseModel):
    """Signal from market regime detection model."""
    regime: Regime
    confidence: float = Field(..., ge=0.0, le=1.0)
    probabilities: Dict[str, float]
    timestamp: float
    model_version: str


class Signal(str, Enum):
    """Trading signal direction."""
    BUY = "buy"
    SELL = "sell"
    HOLD = "hold"


class StrategySignal(BaseModel):
    """Signal generated by a trading strategy."""
    strategy_name: str
    asset: str
    signal: Signal
    confidence: float = Field(..., ge=0.0, le=1.0)
    suggested_size: float
    regime: Regime
    timestamp: float
    metadata: Dict[str, Any] = Field(default_factory=dict)


class FeatureSnapshot(BaseModel):
    """Market feature snapshot for a single asset at a point in time."""
    asset: str
    timeframe: str
    timestamp: float
    ohlcv: Dict[str, float]  # {open, high, low, close, volume}
    indicators: Dict[str, float]
    order_book: Dict[str, Any]
    funding_rate: Optional[float] = None


class OrderSide(str, Enum):
    """Position direction for orders."""
    LONG = "long"
    SHORT = "short"


class Order(BaseModel):
    """Order placed in the market."""
    id: str = Field(default_factory=lambda: str(uuid4()))
    asset: str
    side: OrderSide
    size: float
    price: Optional[float] = None
    order_type: str = Field(default="market")
    exchange: str
    strategy_name: str
    kelly_fraction: float
    regime_at_entry: Regime
    stop_loss: Optional[float] = None
    take_profit: Optional[float] = None
    timestamp: float


class Position(BaseModel):
    """Open position in the market."""
    id: str
    asset: str
    side: OrderSide
    size: float
    entry_price: float
    current_price: float
    unrealized_pnl: float
    stop_loss: float
    strategy_name: str
    exchange: str
    opened_at: float


class FillReport(BaseModel):
    """Report of an executed order fill."""
    order_id: str
    asset: str
    side: OrderSide
    size: float
    fill_price: float
    fee: float
    exchange: str
    slippage: float
    latency_ms: float
    timestamp: float


class StrategyHealth(BaseModel):
    """Health metrics for a trading strategy."""
    name: str
    sharpe_7d: float
    sharpe_30d: float
    win_rate: float = Field(..., ge=0.0, le=1.0)
    total_trades: int
    avg_profit: float
    avg_loss: float
    is_enabled: bool
    is_paper: bool
    regime: str


class ExchangeStatus(BaseModel):
    """Status and performance metrics for an exchange connection."""
    name: str
    status: str = Field(..., pattern="^(healthy|degraded|down)$")
    rtt_p50_ms: float
    rtt_p95_ms: float
    error_rate: float = Field(..., ge=0.0, le=1.0)
    in_fallback: bool


class DegradationTier(str, Enum):
    """System degradation tiers for adaptive strategy management."""
    TIER1_OPERATIONAL = "tier1_operational"
    TIER2_DEGRADED = "tier2_degraded"
    TIER3_CONSERVATIVE = "tier3_conservative"
    TIER4_EMERGENCY = "tier4_emergency"